name: Build and Test
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Installs nightly toolchain
        run: |
          rustup update nightly
          rustup component add rustfmt --toolchain nightly
          rustup default nightly

      - name: Formatting check
        run: cargo fmt --all -- --check

      - name: Run tests
        run: cargo test --all

